export const countries: Record<string, string> = {
  "54": "Argentina",
  "55": "Brazil",
  "56": "Chile",
  "57": "Colombia",
  "20": "Egypt",
  "33": "France",
  "49": "Germany",
  "91": "India",
  "62": "Indonesia",
  "972": "Israel",
  "39": "Italy",
  "60": "Malaysia",
  "52": "Mexico",
  "31": "Netherlands",
  "234": "Nigeria",
  "92": "Pakistan",
  "51": "Peru",
  "7": "Russia",
  "966": "Saudi Arabia",
  "27": "South Africa",
  "34": "Spain",
  "90": "Turkey",
  "971": "United Arab Emirates",
  "44": "United Kingdom",
  "1": "US/Canada",
  "-1": "Rest of World",
};
